version: "3.8"

services:
    app:
        image: 700800900/crew-laravel-api:latest
        container_name: crew-api
        ports:
            - "8080:80"
        env_file:
            - .env
        depends_on:
            - db
        volumes:
            - ./storage:/var/www/html/storage
            - ./bootstrap/cache:/var/www/html/bootstrap/cache

    db:
        image: mysql:8.0
        container_name: crew-db
        restart: always
        environment:
            MYSQL_DATABASE: min-lara-react-app
            MYSQL_USER: root
            MYSQL_PASSWORD: ""
            MYSQL_ROOT_PASSWORD: ""
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
